In [1]:
# imports
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay, classification_report, make_scorer, recall_score, f1_score
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
from sklearn.model_selection import train_test_split, KFold, StratifiedKFold, cross_val_score, cross_validate
from sklearn.preprocessing import StandardScaler 
from sklearn.linear_model import LogisticRegression, LinearRegression
import warnings

from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error

# classificacao
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, classification_report, confusion_matrix

In [2]:
df = pd.read_csv('db/creditCleanCard.csv', sep=',')
df.head()

id  lim_credito  sexo  educacao  est_civil  idade  sts_1  sts_2  sts_3  \
0   1      20000.0     2         2          1     24     -2     -2     -1   
1   2     120000.0     2         2          2     26      2      0      0   
2   3      90000.0     2         2          2     34      0      0      0   
3   4      50000.0     2         2          1     37      0      0      0   
4   5      50000.0     1         2          1     57      0      0      0   

   sts_4  ...  fatura_5  fatura_6  v_pg_1  v_pg_2  v_pg_3   v_pg_4   v_pg_5  \
0     -1  ...    3102.0    3913.0     0.0     0.0     0.0      0.0    689.0   
1      0  ...    1725.0    2682.0  2000.0     0.0  1000.0   1000.0   1000.0   
2      0  ...   14027.0   29239.0  5000.0  1000.0  1000.0   1000.0   1500.0   
3      0  ...   48233.0   46990.0  1000.0  1069.0  1100.0   1200.0   2019.0   
4     -1  ...    5670.0    8617.0   679.0   689.0  9000.0  10000.0  36681.0   

   v_pg_6       aux  inadimplente  
0     0.0    7015.0             1  
1     0.0   12077.0             1  
2  1518.0   90635.0             0  
3  2000.0  222946.0             0  
4  2000.0   50290.0             0  

[5 rows x 26 columns]

MODELOS

In [3]:
X, y = df.drop(columns="aux"), df['aux']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.15, random_state= 42)

X.shape, y.shape

((28282, 25), (28282,))

In [4]:
modelLLR = LogisticRegression()
modelLR  = LinearRegression()

In [5]:
modelLLR.fit(X_train, y_train)

c:\Users\Polga-Fe\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [6]:
y_pred_LLR = modelLLR.predict(X_test)

y_pred_LLR[: 10]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [7]:
accuracy_score(y_test, y_pred_LLR)

0.7819938722601932

In [8]:
y_pred_LLR_reduce = np.zeros(y_test.shape[0])
y_pred_LLR_reduce[:10]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [9]:
print(classification_report(y_test, y_pred_LLR))


              precision    recall  f1-score   support

           0       0.78      1.00      0.88      3318
           1       0.00      0.00      0.00       925

    accuracy                           0.78      4243
   macro avg       0.39      0.50      0.44      4243
weighted avg       0.61      0.78      0.69      4243



c:\Users\Polga-Fe\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\Polga-Fe\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\Polga-Fe\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(av

In [10]:
print(classification_report(y_test, y_pred_LLR_reduce))

              precision    recall  f1-score   support

           0       0.78      1.00      0.88      3318
           1       0.00      0.00      0.00       925

    accuracy                           0.78      4243
   macro avg       0.39      0.50      0.44      4243
weighted avg       0.61      0.78      0.69      4243



c:\Users\Polga-Fe\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\Polga-Fe\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\Polga-Fe\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(av

SCALER

In [11]:
scaler  = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test  = scaler.transform(X_test) 

In [12]:
modelLLRS = LogisticRegression(max_iter=200, solver='saga')
modelLLRS.fit(X_train, y_train)

c:\Users\Polga-Fe\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_sag.py:349: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(


LogisticRegression(max_iter=200, solver='saga')

In [13]:
y_pred_LLRS = modelLLR.predict(X_test)
print(y_pred_LLRS)


[0 0 0 ... 0 0 0]


c:\Users\Polga-Fe\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


In [14]:
print(classification_report(y_test, y_pred_LLRS))


              precision    recall  f1-score   support

           0       0.88      0.50      0.64      3318
           1       0.30      0.75      0.42       925

    accuracy                           0.56      4243
   macro avg       0.59      0.63      0.53      4243
weighted avg       0.75      0.56      0.59      4243

